### ISSUE TITLE
Add student work completion statistics to database

### ISSUE THREAD

**Issue by JDC-horizons** [boolean-uk/team-dev-server-c13#22]
Objective is to add information to database which tracks exercises, units and modules each student has completed. 

Table Exercises:
- id Int
- name String
- description? String
- unitId Int
- unit @relation

Table Units:
- id Int
- name String
- description? String
- moduleId Int
- module @relation
- exercises [ ]

Table Modules:
- id Int
- name String
- description? String
- units [ ]

Table Grades:
- id Int
- exerciseId Int
- exercise @relation
- userId Int
- user @relation
- grade Int
- completedAt dateTime default(now)

From this each student relates to grades, which can then inform which units and furthermore modules they have completed.

Suggested data structure:

- Module 1 -> Unit 1 + 2
- Module 2 -> Unit 3
- Module 3 -> Unit 4 + 5
- Unit 1 -> Exercise 1 + 2
- Unit 2 -> Exercise 3 + 4 + 5
- Unit 3 -> Exercise 6 + 7
- Unit 4 -> Exercise 8 + 9 + 10
- Unit 5 -> Exercise 11 + 12

**Comment by dogezen** [comment]
OK - not very convinced about this:

Do we have a Modules, Units and Exercises tables? I would imagine an exercise is linked to a unit, which in turn is then linked to a module?

if we have these tables, then we should simply add a table CompletedExercises which links 1 exercise to 1 user. You can then add a table  UnitParticipations or something similar where you link a student to a specific unit. In this way you can fetch the student's units. 

With all this info, you know exactly how much stuff has been completed.

In any case, if you choose instead to have a simple counters table, it's also OK, but just confirm this is what you'll go for and I would not call it `Work` because that's unclear. It could be called `StudentCourseCompletionStatistics` or something like that. However if it's just # of exercises, etc it wont really help us know if a student has actually completed that course

**Comment by ezeikel** [comment]
Maybe there should be a `completedAt` field? or do you think the `createdAt` from Grade would server that purpose? @JDC-horizons

**Comment by dogezen** [comment]
Exercises might have a description? Or a Github URL?
Modules and units might also benefit from a description?
Description can be optional, no need to force it

As Ezekiel mentions, the Grades should have a completedAt / or createdAt / updatedAt fields.
