### ISSUE TITLE
Post Creation

### ISSUE THREAD

**Issue by JDC-horizons** [boolean-uk/team-dev-server-c13#8]
expected request would be:
auth contains userId, body contains post content 

POST request to /posts endpoint  
inside controllers > post.js 

inside function create, (content pulled from request body, userId pulled from request auth):

prisma.post.create{ data: {
content: content,
userId: userId,
}}

if user not logged in => return 401 error
if content not provided => return 400 error

then add created post to response 
if successful => return 201 and post contents

add 401 error to API spec.

**Comment by dogezen** [comment]
Can you link to the FIGMA design of this component?
Can you include how many components you want to create? Which names? where these should be created (file-wise)?
Can you include where you need to then instantiate the components? On which page?

**Comment by dogezen** [comment]
Thanks for pointing out - saw the server label right now.

What's not clear to me then from the description is:

a) what is the endpoint that the client needs to use ie, POST /posts with payload being {...}; of the payload, are there any requirements? ie is content allowed to be an empty string? or null, or missing? etc...
b) what kind of errors are you going to return?
c) do you need to update the openapi spec?
d) does this endpoint need authorization?
e) can I create a post for a different user? where is the userId coming from? the authorization or the body? (check carefully, what the authorization functions do, if they make available the user to you or whether you do have to expect the userId from the body of the request)
f) you are adding these two properties:

likes Int @default(0)
comments Comment[]

I think these should be designed as separate issues because both can require a big number of changes: for example, creating a comment should be a different endpoint and not part of creating post, so I wou;dn't expect creating a post to need to touch Comments just yet. Same with likes, how do you know who liked that post, so that that person can remove the like? you'd need to create a Likes table and store which user liked which post and avoid duplicates and so on, so that would probably be added when you design liking / unliking posts, so I'd exclude the change to the model just now

**Comment by ezeikel** [comment]
If this is only for the API/Server implementation of creating a post, I wouldn't mention any of the UI things in the ticket. It could just be as simple as:

1. This is the endpoint I'm going to create .e.g POST /create/something
2. Here is what is expected In the req.body..
3. Here is what errors will be returned from endpoint..
4. Here is what will be returned on success
5. Any updates to openai yaml file if needed to update API documentation

Like @dogezen mentioned I would keep it really minimal to start off with. After the completion of this ticket we should be able to at least just create a post. All the other more complicated aspects could be additional tickets after this one
