### ISSUE TITLE
Register New User Profile

### ISSUE THREAD

**Issue by zainabch123** [boolean-uk/team-dev-server-c13#9]
PLAN: 
1. Client side updates user profile uses a patch request therefore change updateById function (in controllers → users.js) to accept userId and profile details (e.g. first name, last name, bio)
2. Get unique user using user id
3. If user.id not userToUpdate id OR user.role not teacher, return error.
4. Create updateData variable. 
5. If user is a  teacher then updateData includes cohortId (as only teacher can update cohortId).
8. If user is correct user then updateData includes profile data (e.g. firstName, lastName etc).
9. Finally update user according to updateData.
10. Also need to change validateTeacher function in middleware → auth.js to allow the users to update profiles as well.

**Comment by dogezen** [comment]
If I were to code this, there's a bit too much flexibility in the design:

1. why not propose the function signature you want?: `function updateById(userId, profileData)` where `profileData` has the following payload:

```js
{
 firstName: string,
 lastName: string,
}
```

etc.. ; you should also specify if the strings can be null, empty or need a value...

2. where should I write the code for getting the user by unique id? what change needs to happen here? not clear what I need doing with point 2
3. ok, i understand points 2 and 3 are pseudocode for the logic of updateById, then in that case I'd expect the design to be:


Proposal for the logic for `updateById` defined above
```js
get fields from req.body (TODO: define if they can be null, empty, undefined etc..., this info is misisng from your design)
fetch user by id from db to check user actually exists -> return error if not (what error, etc)
check whoever sent the request has permissions for request -> return error if not (what error message, what status code)
define updateData
etc...
```

You also mention to update the validateTeacher function so that students can also update profile -> I think this needs elaboration if you have a solution to this so if I end up picking up this issue I know exactly what to do (ie. do you want me to create a different validate function, or modify the existing validate function, but in what way would you expect the function to be changed and would that change be appropriate?)

And then you'd want to include:

a) which files all this logic should go
b) are you changing any router? any controller?
c) is the model going to change?

**Comment by zainabch123** [comment]
NEW PLAN:
1. Change function updateById to get following fields from req.body: firstName(required), lastName(required), biography(optional), githubUrl(optional). Also ensure updateById function can get userId from req.params.
2. In the updateById function , get user by id from db. If user does not exist, return error 400: 'User does not exist'.
3. Verify if user is allowed to change this users info/profile. This involves verifying if user is a teacher or if user.id matches the user we are about to update. **A potential solution is to change the validateTeacherRole function in middleware → auth.js file. ** Return error 403: "User not authorised" if user does not have permission. 
4. Once checks have been completed in the updateById function, define a variable called 'updateData'. Use if statements to define the following logic: 
- If user is a teacher then updateData includes cohortId (as only teacher can update cohortId).
- If user is correct user then updateData includes profile data (e.g. firstName, lastName etc).
5. Finally update prisma.user according to the updateData.

**Comment by dogezen** [comment]
ok, for point 3: just make sure the loggedin user id of the authorization token matches the given user id from req.params for the api call (or body); don't modify validateTeacherRole
